/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CalculadorasRouteImport } from './routes/calculadoras'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as MetodologiasRouteImport } from './routes/metodologias'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FerramentasIndexRouteImport } from './routes/ferramentas.index'
import { Route as FerramentasLoginRouteImport } from './routes/ferramentas.login'
import { Route as FerramentasSocialRouteImport } from './routes/ferramentas.social'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasRoute = CalculadorasRouteImport.update({
  id: '/calculadoras',
  path: '/calculadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiasRoute = MetodologiasRouteImport.update({
  id: '/metodologias',
  path: '/metodologias',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const FerramentasIndexRoute = FerramentasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasLoginRoute = FerramentasLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasSocialRoute = FerramentasSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => FerramentasRoute,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadoras': typeof CalculadorasRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/indicadores': typeof IndicadoresRoute
  '/metodologias': typeof MetodologiasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ferramentas/login': typeof FerramentasLoginRoute
  '/ferramentas/social': typeof FerramentasSocialRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadoras': typeof CalculadorasRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/indicadores': typeof IndicadoresRoute
  '/metodologias': typeof MetodologiasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ferramentas/login': typeof FerramentasLoginRoute
  '/ferramentas/social': typeof FerramentasSocialRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/ferramentas': typeof FerramentasIndexRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadoras': typeof CalculadorasRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/indicadores': typeof IndicadoresRoute
  '/metodologias': typeof MetodologiasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ferramentas/login': typeof FerramentasLoginRoute
  '/ferramentas/social': typeof FerramentasSocialRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/calculadoras'
    | '/cases'
    | '/contato'
    | '/diagnostico'
    | '/ferramentas'
    | '/indicadores'
    | '/metodologias'
    | '/blog/$slug'
    | '/ferramentas/login'
    | '/ferramentas/social'
    | '/servicos/$slug'
    | '/blog/'
    | '/ferramentas/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadoras'
    | '/cases'
    | '/contato'
    | '/diagnostico'
    | '/indicadores'
    | '/metodologias'
    | '/blog/$slug'
    | '/ferramentas/login'
    | '/ferramentas/social'
    | '/servicos/$slug'
    | '/blog'
    | '/ferramentas'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/calculadoras'
    | '/cases'
    | '/contato'
    | '/diagnostico'
    | '/ferramentas'
    | '/indicadores'
    | '/metodologias'
    | '/blog/$slug'
    | '/ferramentas/login'
    | '/ferramentas/social'
    | '/servicos/$slug'
    | '/blog/'
    | '/ferramentas/'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalculadorasRoute: typeof CalculadorasRoute
  CasesRoute: typeof CasesRoute
  ContatoRoute: typeof ContatoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  FerramentasRoute: typeof FerramentasRouteWithChildren
  IndicadoresRoute: typeof IndicadoresRoute
  MetodologiasRoute: typeof MetodologiasRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras': {
      id: '/calculadoras'
      path: '/calculadoras'
      fullPath: '/calculadoras'
      preLoaderRoute: typeof CalculadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologias': {
      id: '/metodologias'
      path: '/metodologias'
      fullPath: '/metodologias'
      preLoaderRoute: typeof MetodologiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/ferramentas/': {
      id: '/ferramentas/'
      path: '/'
      fullPath: '/ferramentas/'
      preLoaderRoute: typeof FerramentasIndexRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/login': {
      id: '/ferramentas/login'
      path: '/login'
      fullPath: '/ferramentas/login'
      preLoaderRoute: typeof FerramentasLoginRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/social': {
      id: '/ferramentas/social'
      path: '/social'
      fullPath: '/ferramentas/social'
      preLoaderRoute: typeof FerramentasSocialRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface FerramentasRouteChildren {
  FerramentasLoginRoute: typeof FerramentasLoginRoute
  FerramentasSocialRoute: typeof FerramentasSocialRoute
  FerramentasIndexRoute: typeof FerramentasIndexRoute
}

const FerramentasRouteChildren: FerramentasRouteChildren = {
  FerramentasLoginRoute: FerramentasLoginRoute,
  FerramentasSocialRoute: FerramentasSocialRoute,
  FerramentasIndexRoute: FerramentasIndexRoute,
}

const FerramentasRouteWithChildren = FerramentasRoute._addFileChildren(
  FerramentasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CalculadorasRoute: CalculadorasRoute,
  CasesRoute: CasesRoute,
  ContatoRoute: ContatoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  FerramentasRoute: FerramentasRouteWithChildren,
  IndicadoresRoute: IndicadoresRoute,
  MetodologiasRoute: MetodologiasRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
